Adding A  Fixed  The Navagation  Bar
officailesse/MicroversePortfolioProject pull request #1
Opened 2022-04-20 19:06 UTC by officailesse

displaying   navigation bar properly

2022-04-21 21:00 UTC, ShahierNashaat requested changes
Hi @officailesse , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 21:00 UTC, ShahierNashaat commented on index.html
> +    </header>
- [ ] kindly be noticed that the header tag should have the following.
- The logo (if the design has one) is on the left and has a link (a tag).
- The hamburger button is on the right and has a `nav` tag.

- [ ] Also be noticed that the content of the header is aligned with the flexbox.

2022-04-21 21:00 UTC, ShahierNashaat commented on index.html
> +    </div>
- [ ] Kindly wrap all of this inside a `section` tag.
- Also be noticed that you should add the list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag) inside the `section` tag.

- [ ] Also be noticed that the content of the section is aligned with flexbox

2022-04-21 21:00 UTC, ShahierNashaat commented on index.html
> +    </div>
- [ ] Kindly be noticed that the section has the proper background image (decorations are always background images, not `img` tags)

2022-04-22 16:21 UTC, JuliCarracedo approved these changes
# Status: Approved✔️
Hi @officailesse , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 15:12 UTC, merged